package io.kid1999.esystem.entity;

import java.io.Serializable;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

/**
 * @TableName address
 */
@Data
public class Address implements Serializable {
    /**
     * 
     *
     * @mbg.generated Mon Jan 18 11:33:06 CST 2021
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 
     *
     * @mbg.generated Mon Jan 18 11:33:06 CST 2021
     */
    private String address;

    /**
     * 
     *
     * @mbg.generated Mon Jan 18 11:33:06 CST 2021
     */
    private String province;

    /**
     * 
     *
     * @mbg.generated Mon Jan 18 11:33:06 CST 2021
     */
    private String city;

    /**
     * 
     *
     * @mbg.generated Mon Jan 18 11:33:06 CST 2021
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Mon Jan 18 11:33:06 CST 2021
     */
    private static final long serialVersionUID = 1L;
}