package io.kid1999.esystem.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @TableName collection
 */
@Data
public class Collection implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sun Jan 03 17:57:20 CST 2021
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 17:57:20 CST 2021
     */
    private Long userId;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 17:57:20 CST 2021
     */
    private Long goodsId;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 17:57:20 CST 2021
     */
    private LocalDateTime createDate;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 17:57:20 CST 2021
     */
    @TableLogic
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection
     *
     * @mbg.generated Sun Jan 03 17:57:20 CST 2021
     */
    private static final long serialVersionUID = 1L;
}