package io.kid1999.esystem.entity;

import java.io.Serializable;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

/**
 * @TableName contact_way
 */
@Data
public class ContactWay implements Serializable {
    /**
     * 
     *
     * @mbg.generated Tue Jan 05 13:22:52 CST 2021
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 
     *
     * @mbg.generated Tue Jan 05 13:22:52 CST 2021
     */
    private String email;

    /**
     * 
     *
     * @mbg.generated Tue Jan 05 13:22:52 CST 2021
     */
    private String other;

    /**
     * 
     *
     * @mbg.generated Tue Jan 05 13:22:52 CST 2021
     */
    private String phone;

    /**
     * 
     *
     * @mbg.generated Tue Jan 05 13:22:52 CST 2021
     */
    private String qq;

    /**
     * 
     *
     * @mbg.generated Tue Jan 05 13:22:52 CST 2021
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact_way
     *
     * @mbg.generated Tue Jan 05 13:22:52 CST 2021
     */
    private static final long serialVersionUID = 1L;
}