package io.kid1999.esystem.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @TableName demand
 */
@Data
public class Demand implements Serializable {
    /**
     * 
     *
     * @mbg.generated Mon Jan 04 16:02:01 CST 2021
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 
     *
     * @mbg.generated Mon Jan 04 16:02:01 CST 2021
     */
    private String title;

    /**
     * 
     *
     * @mbg.generated Mon Jan 04 16:02:01 CST 2021
     */
    private String decription;

    /**
     * 
     *
     * @mbg.generated Mon Jan 04 16:02:01 CST 2021
     */
    private String imgUrl;

    /**
     * 
     *
     * @mbg.generated Mon Jan 04 16:02:01 CST 2021
     */
    private LocalDateTime createTime;

    /**
     * 
     *
     * @mbg.generated Mon Jan 04 16:02:01 CST 2021
     */
    private Byte status;

    /**
     * 
     *
     * @mbg.generated Mon Jan 04 16:02:01 CST 2021
     */
    @TableLogic
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demand
     *
     * @mbg.generated Mon Jan 04 16:02:01 CST 2021
     */
    private static final long serialVersionUID = 1L;
}