package io.kid1999.esystem.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @TableName join_activity
 */
@Data
public class JoinActivity implements Serializable {
    /**
     * 
     *
     * @mbg.generated Mon Jan 18 18:11:11 CST 2021
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 
     *
     * @mbg.generated Mon Jan 18 18:11:11 CST 2021
     */
    private Long userId;

    /**
     * 
     *
     * @mbg.generated Mon Jan 18 18:11:11 CST 2021
     */
    private Long activityId;

    /**
     * 
     *
     * @mbg.generated Mon Jan 18 18:11:11 CST 2021
     */
    private LocalDateTime joinTime;

    /**
     * 
     *
     * @mbg.generated Mon Jan 18 18:11:11 CST 2021
     */
    @TableLogic
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table join_activity
     *
     * @mbg.generated Mon Jan 18 18:11:11 CST 2021
     */
    private static final long serialVersionUID = 1L;
}