package io.kid1999.esystem.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import lombok.Data;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Collection;

/**
 * @TableName user
 */
@Data
public class User implements Serializable, UserDetails {
    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private Long addressId;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private String avatarUrl;

    /**
     *
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private String role;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private Long contactWayId;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private LocalDateTime createTime;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private LocalDateTime lastLoginTime;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private Long loginTimes;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private String username;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private String password;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private String signature;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    @TableLogic
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private static final long serialVersionUID = 1L;



    // 实现UserDetail的验证方法

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return null;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public boolean isAccountNonExpired() {
        return false;
    }

    @Override
    public boolean isAccountNonLocked() {
        return false;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return false;
    }

    @Override
    public boolean isEnabled() {
        return false;
    }
}