package io.kid1999.esystem.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import lombok.Data;

/**
 * @TableName user
 */
@Data
public class User implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private Long addressId;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private String avatarUrl;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private Long contactWayId;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private LocalDateTime createTime;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private LocalDateTime lastLoginTime;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private Long loginTimes;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private String userName;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private String userPwd;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private String signature;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    @TableLogic
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sun Jan 03 22:00:27 CST 2021
     */
    private static final long serialVersionUID = 1L;
}